package com.chatapp.entity;

// default package
// Generated Jul 5, 2015 7:10:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "chatapp")
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	@JsonManagedReference
	private Set<Message> messages = new HashSet<Message>(0);
	@JsonBackReference
	private Set<Chatroom> chatrooms = new HashSet<Chatroom>(0);

	public User() {
	}

	public User(String name, Set<Message> messages, Set<Chatroom> chatrooms) {
		this.name = name;
		this.messages = messages;
		this.chatrooms = chatrooms;
	}

	public User(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "userchatroom", catalog = "chatapp", joinColumns = { @JoinColumn(name = "ufid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cfid", nullable = false, updatable = false) })
	public Set<Chatroom> getChatrooms() {
		return this.chatrooms;
	}

	public void setChatrooms(Set<Chatroom> chatrooms) {
		this.chatrooms = chatrooms;
	}

}
